### ISSUE TITLE
download twitter videos

### ISSUE THREAD

**Issue by rajraman786** [rajraman786/Video-Downloader#12]
make our project download video from twitter

**Comment by Aniket-508** [comment]
I want to work on this but I needed some help too! @rajraman786

**Comment by rajraman786** [comment]
@Aniket-508 work on it for any help dm in discord

**Comment by Aniket-508** [comment]
@rajraman786 Which discord actually?

**Comment by rajraman786** [comment]
@Aniket-508 is your script ready ?
