### ISSUE TITLE
[Bug]: Video Download page showing error

### ISSUE THREAD

**Issue by KKhushhalR2405** [rajraman786/Video-Downloader#14]
<img src="https://user-images.githubusercontent.com/58569950/147357940-d9f2d753-92c3-4389-a60d-c6f48f862854.png" width="700" height="300" />

<img src="https://user-images.githubusercontent.com/58569950/147358069-eef8904b-9574-4d34-8059-d0a6fb3d61ef.png" width="700" height="300" />

Can I solve this issue?

**Comment by rajraman786** [comment]
@KKhushhalR2405 after putting URL you didn't check the checkbox for download video from youtube that's why it showing error

**Comment by KKhushhalR2405** [comment]
![image](https://user-images.githubusercontent.com/58569950/147390551-31080cf2-e91c-4fb7-955a-467439134198.png)

![image](https://user-images.githubusercontent.com/58569950/147390560-7a188dfb-d083-473c-a7e9-f933ddf54355.png)

**Comment by rajraman786** [comment]
@KKhushhalR2405 it is the error with the deploy 
you first set up this project on your PC .
and for setup follow the pinned msg of the python channel of the discord group.

then you will find the project is working fine .
