### ISSUE TITLE
CREATE README.md

### ISSUE THREAD

**Issue by rajraman786** [rajraman786/Video-Downloader#2]
Update the readme file of the project which consists of all information of the project .
note-- use gifs or screenshots in the readme to make readme more visual about project .

**Comment by SachinMittal1766** [comment]
@rajraman786 I would like to work on it. pls assign it to me.

**Comment by rajraman786** [comment]
@SachinMittal1766 you are still working on this ?

**Comment by SachinMittal1766** [comment]
Yes, currently I am studying about README.md file
