### ISSUE TITLE
setup path for downloading

### ISSUE THREAD

**Issue by rajraman786** [rajraman786/Video-Downloader#4]
For now, the video starts downloading in the same folder of the project.
make the project to first ask the path and after specifying the path our video starts downloading .

**Comment by shobhit10058** [comment]
I would like to work for this issue. I am thinking to send the file as attachment to client and deleting the file in server after this.

**Comment by rajraman786** [comment]
@shobhit10058  great work! 
It works fine for youtube videos make this same for the second option also ( i.e for downloading videos from other websites ).
[use this ](http://www.howtowebscrape.com/examples/media/images/BigRabbit.mp4) link for testing the second option .

**Comment by shobhit10058** [comment]
@rajraman786 This works for [this ](http://www.howtowebscrape.com/examples/media/images/BigRabbit.mp4) link also.

**Comment by rajraman786** [comment]
> @rajraman786 This works for [this ](http://www.howtowebscrape.com/examples/media/images/BigRabbit.mp4) link also.

check again for this link and turn on 2nd checkbox .
without asking the path it plays the video in the browser.

**Comment by shobhit10058** [comment]
![image](https://user-images.githubusercontent.com/56156171/145699333-258550f8-4e93-4541-887f-8d2234c479a7.png)
It is coming like this now.

**Comment by rajraman786** [comment]
ok, I will check it.
